### ISSUE TITLE
Solix Smart Meter

### ISSUE THREAD

**Issue by Bascht74** [thomluther/ha-anker-solix#121]
## System Information

version | core-2024.8.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.46-haos
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.0
Stage | running
Available Repositories | 1399
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 4. November 2024 um 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-2.ui.nabu.casa
certificate_status | ready
instance_id | daf6eb36bef7465f8c634aa2297f31b0
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 113.9 GB
disk_used | 44.9 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | MariaDB (2.7.1), Advanced SSH & Web Terminal (18.0.0), Studio Code Server (5.15.0), UniFi Network Application (3.2.0), ESPHome (2024.8.3), RaspberryMatic CCU (3.77.7.20240826), phpMyAdmin (0.9.1), Home Assistant Google Drive Backup (0.112.1), EMHASS (0.10.6)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 3
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 8. August 2024 um 12:04
-- | --
current_recorder_run | 3. September 2024 um 10:32
estimated_db_size | 3706.36 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Integration version

2.1.1

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

My Solix Smart Meter does send a lot of "zero" values between real data. I know this is because of the way the api works, but can you suppress those data sets?

### Reproduction steps

1. Add Solix Smart Meter to your system
2. View the data

### Debug logs

```text
What do you need here excaclty?
```

### Diagnostics dump

I am not able to get it. It is not shown:
<img width="378" alt="image" src="https://github.com/user-attachments/assets/9401f993-e6a3-48ba-9350-1bb71fc5d76e">

Here is a graph that shows my problem:
<img width="1204" alt="image" src="https://github.com/user-attachments/assets/f1cdc6dc-af98-4f4e-9d00-3e499358f55d">

**Comment by thomluther** [comment]
@Bascht74 I cannot suppress individual 0W data because there is no mechanism to detect whether these values are true or false.
The cloud was originally marking invalid data with a separate field, but that was for all power values in the response.
If only your smart meter has false 0W values, you have an issue in your setup.
You can try to change the configuration entry options and skip invalid data responses as described [here](https://github.com/thomluther/ha-anker-solix/blob/main/INFO.md#option-considerations-for-solarbank-2-devices-and-smart-meters), but I don't think this will solve your issue since the cloud should no longer respond invalid data. This cloud change was implemented in June in order to fix the data update issues when using shared accounts which do not trigger frequent data updates either.
